#include "../headers/includes.h"

const char *slr_dlgs[14] = {"Step right up!\nWe've got the finest gear this side of the universe.\nAnd don't worry, we sanitize all items with ASCII-grade soap!",
                            "Looking for an upgrade?\nMaybe some potions to boost your stats?\nI've got it all,\nand at prices that won't break the code!",
                            "Ah, a discerning customer!\nI can tell you have an eye for quality.\nHow about this fine shield? Guaranteed to protect you\nfrom even the nastiest of '@' enemies.",
                            "We're having a sale on healing potions today.\nBuy two, and I might just throw in some extra punctuation for free!",
                            "You look like someone who could use a new pair of boots.\nI've got some here that'll increase your speed by\nat least three exclamation marks!",
                            "Need a map?\nI've got some that'll show you secret locations—hidden\nright behind the walls of text!",
                            "If you're low on currency, I also take trades.\nGot any rare characters? I'm particularly interested in accented\n'e's and umlauts.",
                            "I promise, everything here is totally legal.\nWell, mostly legal. Let's just say it's all very..\nnegotiable.",
                            "New in stock:\nHealth Packs, Energy Orbs, and Mystery Potions!\nWhat's in the Mystery Potions? Well, that's part of the mystery!",
                            "For a limited time, we're offering a 'Buy 1, Get 1 Pixel Free' deal!\nDon't miss out!",
                            "Careful out there.\nThe enemies get stronger with each line you cross.\nBetter stock up before heading out.",
                            "You never know when a good old Potion\nof Invisibility will come in handy.\nJust be careful, you might blend into the text\nand never be found again!",
                            "We've got some rare goods coming in next week.\nYou didn't hear it from me, but I hear there's a\nchance for a legendary '!' sword.",
                            "Remember, all sales are final!\nNot responsible for any glitches,\nbugs, or out-of-bounds errors once\nyou leave the shop."};

const char *forg_dlgs[13] = {"Looking for an upgrade? A new weapon?\nI've got it all, and at prices that\nwon't break the code!",
                             "Ah, a discerning customer!\nI can tell you have an eye for quality.\nHow about this fine shield?\nGuaranteed to protect you from\neven the nastiest of '@' enemies.",
                             "You look like someone who could use a new propulser.\nI've got some here that'll increase your speed by\nat least three exclamation marks!",
                             "If you're low on currency, I also\ntake trades. Got any rare characters?\nI'm particularly interested in\naccented 'e's and umlauts.",
                             "Ah, I see you're eyeing the Laser Cannon 5000.\nA fine choice!\nIt comes with a free trial on moving targets!",
                             "Looking for something unique?\nI've got a vintage ASCII sword.\nStraight from the days of\nthe first text-based RPGs!",
                             "For a limited time, we're offering a 'Buy 1, Get 1 Pixel Free' deal!\nDon't miss out!",
                             "I wouldn't go into the Nebula Zone without a bit more firepower.\nLuckily, I've got just the thing for you:\na pair of Rocket Boots!",
                             "Careful out there.\nThe enemies get stronger with each line you cross.\nBetter stock up before heading out.",
                             "Looking for armor? I have\nASCII-coded armor that'll turn enemy\nhits into mere asterisks.",
                             "We've got some rare goods coming in next week.\nYou didn't hear it from me, but I hear there's\na chance for a legendary '!' sword.",
                             "Oh, you need repairs?\nI've got a friend who can fix that armor right up..\nfor the right price.",
                             "Remember, all sales are final!\nNot responsible for any glitches,\nbugs, or out-of-bounds errors once\nyou leave the shop."};

// SHOPPER Dialogues
const char *shpr_dlgs[20] = {"This is a monster-free zone.\n",
                             "Have you ever wondered if we're just\ncharacters in some giant, cosmic book?\nMakes you think, right?",
                             "I've been saving up for one of those new multi-directional blasters.\nThink it's worth it?",
                             "The Seller's prices are high,\nbut what else are you going to spend your ITEM on?\nThere's no ASCII bank, after all.",
                             "The universe is a strange place.\nI met a talking 'Q' yesterday. Said he was from Sector 7Q.",
                             "I hear there's a sale on health potions today.\nBetter stock up before the next wave of enemies!",
                             "I wonder if we all look the same to the player.\nLike, do they see me as just another 'S'?",
                             "Have you tried the new potion flavors?\nI think I saw a 'Spicy Fireball' one.\nSound dangerous.",
                             "The Seller keeps trying to sell me an ASCII sword.\nI keep telling him, 'I'm a lover, not a fighter!'",
                             "I'm thinking of investing in some heavy armor.\nYou never know when a rogue '&' might come charging at you.",
                             "Is it just me,\nor is everything getting more.. pixelated?\nMaybe I need to upgrade my glasses.",
                             "The best part of the universe?\nNo shortage of shops.\nThe worst part?\nNo shortage of prices.",
                             "I overheard the Quest Giver talking about some 'epic quest'.\nDo you think they pay in coins, or just in XP?",
                             "I tried haggling with the Seller once.         \nEnded up paying more than the original price.\nGo figure.",
                             "What's the deal with those potions?\nSometimes I drink one,\nand I swear my pixels rearrange.",
                             "I've been thinking about starting my own shop.\nMaybe sell some rare punctuation marks.\nThere's always a demand.",
                             "Sometimes, I think we're all just waiting to be typed.\nOther times, I'm just here for the potions.",
                             "WOWI?\n",
                             "I bought a map from the Seller once.\nTurned out it was just a random\ncollection of 'x's and 'y's.",
                             "You ever get the feeling that someone\nout there is just watching us,\nwaiting for us to say something funny?\nWeird, huh?"};

// QUEST GIVER
const char *adv_dlgs[20] = {"Greetings, adventurer!\nI have a task for you. The '@'s in the\nGlyph Forest have been causing trouble.\nCan you thin their numbers?",
                            "A rare artifact has been stolen by\nthe notorious '#' bandits.\nRetrieve it, and you shall be rewarded.",
                            "I need someone brave enough to\nenter the Lost Caves and collect 15 Rare '*' Crystals.\nAre you up for it?",
                            "The Galactic 'Z' Pirates have been spotted in Sector 9.\nTake out 20 of them\nand I'll make it worth your while.",
                            "I have a special quest for you.\nDeep in the Binary Wastes lies the legendary '1' Sword.\nFind it and bring it back.",
                            "There's a bounty on a group of 'X'\nmarauders terrorizing the villagers near the ASCII River.\nTake them down!",
                            "I need someone to deliver this\nencrypted message to\nthe '&' Leader in the Unknown Zone.\nIt's risky, but the rewards are great.",
                            "Rumor has it there's a hidden\ndungeon filled with 'O' monsters.\nClear it out and I'll pay you handsomely.",
                            "Our scouts report that the ancient 'M\ntemple is infested with rogue '+' golems.\nThink you can handle it?",
                            "The King of '~' Land has requested our\nhelp in retrieving a stolen relic.\nAre you brave enough for the journey?",
                            "There's a strange disturbance in the ASCII Sea.\nWe need you to investigate and eliminate any threats.",
                            "The '=' cultists are up to something sinister.\nI need you to infiltrate their\nbase and report back.",
                            "We've lost contact with the expedition\nteam near the Forgotten Monoliths.\nFind them and bring them home.",
                            "A rare plant known as the '&' Flower\ngrows in the Depths of the Undertext.\nBring me five of them, if you dare.",
                            "An evil overlord known as '!' has\ndeclared war on the Punctuation Villages.\nStop him before it's too late.",
                            "The ASCII Mines are filled with\nvaluable '$' gems, but also deadly traps.\nRetrieve the gems and keep half.",
                            "A powerful sorceress '#' has\nbeen raising an army of '*'.\nWe need you to put an end to\nher plans.",
                            "The villagers have complained of a\nrogue '?' lurking in the shadows, causing confusion.\nFind it and bring it to justice.",
                            "There's talk of a secret passage\nleading to the Land of Brackets.\nIf you find it, come back and tell me.",
                            "The ancient scrolls speak of a\nhidden treasure guarded by '(' and ')'.\nBring back proof, and the reward is yours."};
// EXPLORER
const char *expl_dlgs[20] = {"I've journeyed to the Outer Edge,\nwhere the text fades into nothingness.\nIt's a place you'll never forget.",
                             "Did you know there's a hidden\ncave behind the ASCII Falls?\nIt's filled with rare '@' symbols.\nQuite the sight!",
                             "I once found an island made\nentirely of '$' signs.\nTried to take some, but they\nvanished like a bad dream.",
                             "The Eastern Wastes are home to\nthe mysterious '~' creatures.\nThey're friendly.. mostly.",
                             "There's a canyon in the south where\nechoes spell out ancient messages.\nSpooky, if you ask me.",
                             "I've been mapping the stars above.\nDid you know they form the word 'Adventure'\nif you connect them right?",
                             "You should explore the Desert\nof the '-'. It's barren, but there's a legend\nof a hidden treasure beneath the sands.",
                             "I've heard there's a portal that\nleads to the Mirror World, where\nall the letters are backwards.\nCould be worth checking out.",
                             "I stumbled upon a village where everyone\nspeaks in binary. Nice folks,\nif you can decode their language.",
                             "Deep in the Dark Forest, there's an\nabandoned castle built out of '~'.\nI'm still not sure who built it.",
                             "There's a waterfall in the northern\nhills that flows upwards.\nThey say it leads to another realm.",
                             "If you venture into the Whitespace Plains,\nbeware—the emptiness can drive a person mad.",
                             "I found a hidden library that tells the\nstory of our universe in emojis.\nOdd, but fascinating.",
                             "The Forgotten Crypt is rumored to hold the\nLegendary Scroll of the '&'.\nDangerous, but worth the risk.",
                             "I once climbed Mount '^'.\nThe view from the top? You could see all the way\nto the Edge of the Screen.",
                             "There's a strange temple where\neverything is made of semicolons.\nIt's said to be a sacred place of balance.",
                             "The Void Lands are rumored to be\nhome to the Old Gods of Punctuation.\nTread carefully if you ever go there.",
                             "I've explored the Great Wall of Text,\na place where letters move on their own.\nSpooky stuff!",
                             "There's a place called the Bracket Bastion,\nfilled with '[' and ']'.\nIt's a puzzle, but a rewarding one.",
                             "I once found a river made of flowing '@'s.\nThe current was strong,\nbut it led to a secret oasis."};
